### ISSUE TITLE
bundle exec jekyll serve not working

### ISSUE THREAD

**Issue by 89hardy** [89hardy/89hardy.github.io#1]
Throwing up the following error:

```C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag/drop.rb:43:in `page_title': undefined method `[]' for nil:NilClass (NoMethodError)```

**Comment by 89hardy** [comment]
@DarkSector Traceback on ubuntu subsystem:

`hardy89@Zanskar:~/Github/89hardy.github.com$ bundle exec jekyll serve
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
Configuration file: /mnt/c/Users/himan/Documents/GitHub/89hardy.github.com/_config.yml
            Source: /mnt/c/Users/himan/Documents/GitHub/89hardy.github.com
       Destination: /mnt/c/Users/himan/Documents/GitHub/89hardy.github.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: undefined method `[]' for nil:NilClass in 404.html/#excerpt
  Liquid Exception: undefined method `[]' for nil:NilClass in 404.html
                    ------------------------------------------------
      Jekyll 4.1.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
Traceback (most recent call last):
        157: from /home/hardy89/gems/bin/bundle:23:in `<main>'
        156: from /home/hardy89/gems/bin/bundle:23:in `load'
        155: from /home/hardy89/gems/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        154: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        153: from /home/hardy89/gems/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
        152: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
        151: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        150: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
        149: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        148: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        147: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        146: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
        145: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        144: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        143: from /home/hardy89/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        142: from /home/hardy89/gems/bin/jekyll:23:in `<top (required)>'
        141: from /home/hardy89/gems/bin/jekyll:23:in `load'
        140: from /home/hardy89/gems/gems/jekyll-4.1.0/exe/jekyll:15:in `<top (required)>'
        139: from /home/hardy89/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        138: from /home/hardy89/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        137: from /home/hardy89/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        136: from /home/hardy89/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        135: from /home/hardy89/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        134: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        133: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        132: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `each'
        131: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        130: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:36:in `process'
        129: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:65:in `build'
        128: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/command.rb:28:in `process_site'
        127: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:80:in `process'
        126: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:208:in `render'
        125: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:523:in `render_pages'
        124: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:523:in `each'
        123: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:524:in `block in render_pages'
        122: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/site.rb:532:in `render_regenerated'
        121: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:63:in `run'
        120: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:80:in `render_document'
        119: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:127:in `render_liquid'
        118: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        117: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        116: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        115: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        114: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        113: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        112: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        111: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        110: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        109: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        108: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        107: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        106: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        105: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/tags/include.rb:210:in `render'
        104: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        103: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/tags/include.rb:212:in `block in render'
        102: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/inclusion.rb:16:in `render'
        101: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        100: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
         99: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
         98: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
         97: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
         96: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
         95: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
         94: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
         93: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
         92: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         91: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         90: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
         89: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         88: from /home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag.rb:36:in `render'
         87: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
         86: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
         85: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         84: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         83: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
         82: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         81: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
         80: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
         79: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
         78: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
         77: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:45:in `block (2 levels) in render'
         76: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:46:in `evaluate'
         75: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:46:in `loop'
         74: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:47:in `block in evaluate'
         73: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:114:in `interpret_condition'
         72: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:159:in `evaluate'
         71: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `evaluate'
         70: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `each_index'
         69: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
         68: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:197:in `lookup_and_evaluate'
         67: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `[]'
         66: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `public_send'
         65: from /home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag/drop.rb:81:in `description'
         64: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `[]'
         63: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `public_send'
         62: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `excerpt'
         61: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/page.rb:226:in `excerpt'
         60: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/page.rb:226:in `new'
         59: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/page_excerpt.rb:13:in `initialize'
         58: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:63:in `run'
         57: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:80:in `render_document'
         56: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/renderer.rb:127:in `render_liquid'
         55: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
         54: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
         53: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
         52: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
         51: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
         50: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
         49: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
         48: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
         47: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
         46: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         45: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         44: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
         43: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         42: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/tags/include.rb:210:in `render'
         41: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
         40: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/tags/include.rb:212:in `block in render'
         39: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/inclusion.rb:16:in `render'
         38: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
         37: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
         36: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
         35: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
         34: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
         33: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
         32: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
         31: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
         30: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
         29: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         28: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         27: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
         26: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         25: from /home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag.rb:36:in `render'
         24: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
         23: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
         22: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
         21: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
         20: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
         19: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         18: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
         17: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
         16: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
         15: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
         14: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:45:in `block (2 levels) in render'
         13: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:46:in `evaluate'
         12: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:46:in `loop'
         11: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:47:in `block in evaluate'
         10: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/condition.rb:114:in `interpret_condition'
          9: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:159:in `evaluate'
          8: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `evaluate'
          7: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:38:in `each_index'
          6: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
          5: from /home/hardy89/gems/gems/liquid-4.0.3/lib/liquid/context.rb:197:in `lookup_and_evaluate'
          4: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `[]'
          3: from /home/hardy89/gems/gems/jekyll-4.1.0/lib/jekyll/drops/drop.rb:47:in `public_send'
          2: from /home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag/drop.rb:27:in `title?'
          1: from /home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag/drop.rb:50:in `title'
/home/hardy89/gems/gems/jekyll-seo-tag-2.6.1/lib/jekyll-seo-tag/drop.rb:43:in `page_title': undefined method `[]' for nil:NilClass (NoMethodError)
hardy89@Zanskar:~/Github/89hardy.github.com$`

**Comment by DarkSector** [comment]
Tried on my Mac OS as well, failing with same error. So it's not a windows thing

**Comment by DarkSector** [comment]
Okay it's the jekyll-seo-tag plugin that's throwing it off.

Remove that from config and then remove it from default.html and head.html. Commenting it out doesn't work so you'll have to remove it from those files

**Comment by DarkSector** [comment]
```

╭─ ~/Code/playground/89hardy.github.io  master !4 ?1                                                                                                                                                  1 ✘  07:31:09 AM ─╮
╰─                                                                                                                                                                                                                         ─╯
❯ bundle exec jekyll serve --trace
Configuration file: /Users/pronoyc/Code/playground/89hardy.github.io/_config.yml
            Source: /Users/pronoyc/Code/playground/89hardy.github.io
       Destination: /Users/pronoyc/Code/playground/89hardy.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.324 seconds.
 Auto-regeneration: enabled for '/Users/pronoyc/Code/playground/89hardy.github.io'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```

**Comment by 89hardy** [comment]
Got it! Ran it on the local system and yes, it works.

But I restored it back to the original state cos I need the SEO params at the moment for this new site.

**Comment by DarkSector** [comment]
Maybe time to look at git hooks? Like enable SEO before you publish? The SEO changes affect 3 files which are never changed.

**Comment by 89hardy** [comment]
@DarkSector Re-opened this since pages deploy is still failing. Updates here: https://github.com/samarsault/plainwhite-jekyll/issues/107#issuecomment-1009721008
